version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports: 
        - 5555:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo

